"""initial schema

Revision ID: 0e5e7a0cb352
Revises: 
Create Date: 2026-08-29 23:38:27.248169
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision: str = '0e5e7a0cb352'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('flags_upheld', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('handle')
    )
    op.create_table('authsession',
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_handle'], ['user.handle'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_authsession_user_handle'), 'authsession', ['user_handle'], unique=False)
    op.create_table('flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upheld', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['reporter_handle'], ['user.handle'], ),
    sa.ForeignKeyConstraint(['target_handle'], ['user.handle'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flag_target_handle'), 'flag', ['target_handle'], unique=False)
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('previous_price_cents', sa.Integer(), nullable=True),
    sa.Column('condition', sa.Enum('like_new', 'good', 'fair', name='condition'), nullable=False),
    sa.Column('status', sa.Enum('active', 'sold', 'withdrawn', name='listingstatus'), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seller_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sold_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['seller_handle'], ['user.handle'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('buyer_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('unhidden_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_handle'], ['user.handle'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_listing_id'), 'conversation', ['listing_id'], unique=False)
    op.create_table('listingevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listingevent_created_at'), 'listingevent', ['created_at'], unique=False)
    op.create_index(op.f('ix_listingevent_listing_id'), 'listingevent', ['listing_id'], unique=False)
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('rater_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ratee_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['ratee_handle'], ['user.handle'], ),
    sa.ForeignKeyConstraint(['rater_handle'], ['user.handle'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_listing_id'), 'rating', ['listing_id'], unique=False)
    op.create_index(op.f('ix_rating_ratee_handle'), 'rating', ['ratee_handle'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('author_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['author_handle'], ['user.handle'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_created_at'), 'message', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_created_at'), table_name='message')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_rating_ratee_handle'), table_name='rating')
    op.drop_index(op.f('ix_rating_listing_id'), table_name='rating')
    op.drop_table('rating')
    op.drop_index(op.f('ix_listingevent_listing_id'), table_name='listingevent')
    op.drop_index(op.f('ix_listingevent_created_at'), table_name='listingevent')
    op.drop_table('listingevent')
    op.drop_index(op.f('ix_conversation_listing_id'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_table('listing')
    op.drop_index(op.f('ix_flag_target_handle'), table_name='flag')
    op.drop_table('flag')
    op.drop_index(op.f('ix_authsession_user_handle'), table_name='authsession')
    op.drop_table('authsession')
    op.drop_table('user')
    # ### end Alembic commands ###
